---
title: "02-24-2026"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(mosaic)
s<-rnorm(n =100, mean =2, sd = 4)
mean(s)
sd(s)
reps<- 1000
```

T Distributions

```{r}
plotDist("t", df=100, xlab = "x", ylab = "Frequency", col = "red")
plotDist("t", df=100, xlab = "x", ylab = "Frequency", col = "red", add = TRUE)

x<- do(reps) * mean(rt(n =100, df =99, ncp =2))
histogram(~mean, data =x)
plotDist("beta", shape1 = 2, shape2 = 4, xlab = "x", xlim = c(0,1) , ylab = "Frequency")
x<- do(reps) * mean(rbeta(n=100, shape1 = 0.3, shape2 = 4))
sd(x$mean)

```
key functions:
r_(n = ): draws random samples of size n given distribution
p_(q = ): returns the quantile associated with a given value of x
q_(p = ): returns the value of x at a given quantile through the distribution
d_(x = ): returns the value of the probability density function (pdf) at the values of x

```{r}
pnorm(q = 0, mean =0, sd =1)
qnorm(p = c(0.025, 0.975), mean =0, sd =1)
qbeta(p = c(0.025, 0.975), shape1 = 2, shape2 =4)
lower<- qbeta(0.025, shape1 =2, shape2 =4)
upper<- qbeta(0.975, shape1 =2, shape2 =4)
curve(dbeta(x, shape1 =2, shape2 =4), from =0, to =1 , lwd =2)
x<- seq(lower, upper, length =500)
polygon(c(lower,x, upper),
        c(0, dbeta(x, shape1 =2, shape2 =4), 0),
          col = "lightblue")
pbeta(q =0.2, shape1 =2, shape2 =4)
qbeta(p =0.5, shape1=2, shape2=4)
```
